#!/usr/bin/env python3
"""Run all analysis for the 3 new conditions: activation_patching, cot_matched, topk_gated.

Steps:
  1. Extract tar/new_data.tar.gz into workspace/ (if not already done)
  2. Run exp_b_patching.py  (activation_patching data)
  3. Run exp_q_gated.py     (topk_gated data)
  4. Run report.py          (regenerate accuracy/headline with cot_matched)
  5. Copy new JSONs into results/
  6. Write results/new_conditions_summary.txt

Usage:
  python run_new_analysis.py
"""
from __future__ import annotations

import json
import shutil
import subprocess
import sys
import tarfile
from pathlib import Path

ROOT = Path(__file__).resolve().parent
ACT_DIR = ROOT / "workspace" / "activations"
TAR_PATH = ROOT / "tar" / "new_data.tar.gz"
RESULTS = ROOT / "results"


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def run_script(rel_path: str) -> bool:
    cmd = [sys.executable, rel_path, "--activations_dir", str(ACT_DIR)]
    print(f"\n>>> {' '.join(cmd)}")
    result = subprocess.run(cmd, cwd=str(ROOT))
    if result.returncode != 0:
        print(f"WARNING: {rel_path} exited with code {result.returncode}")
        return False
    return True


def load_json(p: Path):
    if not p.exists():
        return None
    with open(p) as f:
        return json.load(f)


def copy_results(exp_name: str):
    src = ACT_DIR / "results" / exp_name
    dst = RESULTS / exp_name
    if not src.exists():
        print(f"  [skip copy] {src} not found")
        return
    dst.mkdir(parents=True, exist_ok=True)
    for f in src.iterdir():
        shutil.copy2(f, dst / f.name)
    print(f"  [copied] {src} -> {dst}")


# ---------------------------------------------------------------------------
# Step 1: Extract tar
# ---------------------------------------------------------------------------

def extract_tar():
    needed = [
        ACT_DIR / "activation_patching",
        ACT_DIR / "cot_matched",
        ACT_DIR / "topk_gated",
    ]
    if all(p.exists() for p in needed):
        print("[step 1] All 3 condition folders already present, skipping extraction.")
        return
    if not TAR_PATH.exists():
        print(f"ERROR: tar not found at {TAR_PATH}")
        print("  Download new_data.tar.gz from RunPod and place it in tar/")
        sys.exit(1)
    print(f"[step 1] Extracting {TAR_PATH} -> workspace/")
    workspace = ROOT / "workspace"
    with tarfile.open(TAR_PATH, "r:gz") as tf:
        tf.extractall(workspace)
    print("  Done.")


# ---------------------------------------------------------------------------
# Step 2-4: Run analysis scripts
# ---------------------------------------------------------------------------

def run_analysis():
    print("\n[step 2] Exp B: activation patching")
    b_ok = run_script("analysis/exp_b_patching.py")

    print("\n[step 3] Exp Q: gated communication (topk_gated)")
    q_ok = run_script("analysis/exp_q_gated.py")

    print("\n[step 4] Report: regenerate accuracy/headline (includes cot_matched)")
    r_ok = run_script("analysis/report.py")

    return b_ok, q_ok, r_ok


# ---------------------------------------------------------------------------
# Step 5: Copy new JSONs into project-root results/
# ---------------------------------------------------------------------------

def sync_results():
    print("\n[step 5] Syncing new results into results/")
    for exp in ("exp_b", "exp_q", "report"):
        copy_results(exp)


# ---------------------------------------------------------------------------
# Step 6: Write summary text
# ---------------------------------------------------------------------------

def write_summary():
    out_path = RESULTS / "new_conditions_summary.txt"
    lines = []

    def h(s):
        lines.append("")
        lines.append("=" * 60)
        lines.append(s)
        lines.append("=" * 60)

    def h2(s):
        lines.append("")
        lines.append(s)
        lines.append("-" * len(s))

    lines.append("NEW CONDITIONS ANALYSIS SUMMARY")
    lines.append("Generated by run_new_analysis.py")
    lines.append("")

    # --- Headline check ---
    h("HEADLINE CHECK (cot_matched baseline)")
    headline = load_json(RESULTS / "report" / "headline_check.json")
    if headline:
        lines.append(f"headline_passed: {headline.get('headline_passed')}")
        lines.append(f"vs_cot_tasks_pass: {headline.get('vs_cot_tasks_pass')} / 3 needed (>=2)")
        lines.append(f"vs_best_of_n_tasks_pass: {headline.get('vs_best_of_n_tasks_pass')} / 3 needed (>=2)")
        lines.append("")
        lines.append("Per-task vs cot_matched:")
        for task, v in headline.get("vs_cot", {}).items():
            if isinstance(v, dict) and not v.get("skipped"):
                lines.append(f"  {task}: LatentMAS {v['lmas_acc']*100:.1f}% vs CoT {v['other_acc']*100:.1f}%"
                             f"  diff={v['diff_pp']:+.1f}pp  p={v['p_value']:.4f}")
            else:
                lines.append(f"  {task}: skipped (condition not collected)")
        lines.append("")
        lines.append("Per-task vs best_of_n:")
        for task, v in headline.get("vs_best_of_n", {}).items():
            if isinstance(v, dict) and not v.get("skipped"):
                lines.append(f"  {task}: LatentMAS {v['lmas_acc']*100:.1f}% vs BoN {v['other_acc']*100:.1f}%"
                             f"  diff={v['diff_pp']:+.1f}pp  p={v['p_value']:.4f}")
            else:
                lines.append(f"  {task}: skipped (best_of_n not yet collected)")
    else:
        lines.append("  [not found]")

    # --- Updated accuracy table ---
    h("UPDATED ACCURACY TABLE")
    acc_path = RESULTS / "report" / "accuracy.csv"
    if acc_path.exists():
        import csv
        with open(acc_path) as f:
            rows = list(csv.DictReader(f))
        TASK_ORDER = ["gsm8k", "arc_challenge", "mbppplus"]
        by_cond = {}
        for r in rows:
            by_cond.setdefault(r["condition"], {})[r["task"]] = r
        lines.append(f"{'Condition':<35} {'GSM8K':>8} {'ARC':>8} {'MBPP+':>8}")
        lines.append("-" * 65)
        for cond, tasks in sorted(by_cond.items()):
            parts = []
            for t in TASK_ORDER:
                if t in tasks:
                    parts.append(f"{float(tasks[t]['accuracy'])*100:>7.1f}%")
                else:
                    parts.append(f"{'---':>8}")
            lines.append(f"{cond:<35} {' '.join(parts)}")
    else:
        lines.append("  [accuracy.csv not found]")

    # --- Exp B: activation patching ---
    h("EXP B: ACTIVATION PATCHING")
    exp_b = load_json(RESULTS / "exp_b" / "exp_b.json")
    if exp_b:
        for t in exp_b.get("per_task", []):
            task = t["task"]
            h2(task)
            lines.append(f"  n_examples:        {t['n_examples']}")
            lines.append(f"  clean accuracy:    {t['clean_accuracy']*100:.1f}%")
            lines.append(f"  corrupt accuracy:  {t['corrupt_accuracy']*100:.1f}%")
            lines.append(f"  Wilcoxon p (clean vs corrupt): {t['wilcoxon_clean_vs_corrupt'].get('p_value', 'n/a'):.4f}")
            lines.append(f"  critical site:     agent {t['critical_agent']}, round {t['critical_round']}")
            lines.append(f"  critical recovery: {t['critical_recovery_rate']*100:.1f}%")
        lines.append("")
        sig = [s for s in exp_b.get("fdr_corrected_sites", []) if s.get("rejected_at_q05")]
        lines.append(f"FDR-significant sites (q<0.05): {len(sig)}")
        for s in sig:
            lines.append(f"  {s['key']}  p={s['p']:.4f}  q={s['q']:.4f}")
    else:
        lines.append("  [exp_b.json not found - run analysis/exp_b_patching.py]")

    # --- Exp Q: gated communication ---
    h("EXP Q: GATED COMMUNICATION (topk_gated)")
    exp_q = load_json(RESULTS / "exp_q" / "exp_q.json")
    if exp_q:
        TASKS = ["gsm8k", "arc_challenge", "mbppplus"]
        for task in TASKS:
            task_data = exp_q.get(task, {})
            if not task_data:
                lines.append(f"  {task}: no data")
                continue
            h2(task)
            for gate, gdata in task_data.items():
                if gate == "confidence_gated_controls":
                    continue
                if not isinstance(gdata, dict) or not gdata.get("n_paired"):
                    continue
                ov = gdata.get("vs_lmas_overall", {})
                lines.append(f"  {gate}:")
                lines.append(f"    n_paired: {gdata['n_paired']}")
                lines.append(f"    vs latent_mas: diff={ov.get('diff_pp', 0):+.1f}pp  p={ov.get('p_value', 1):.4f}")
    else:
        lines.append("  [exp_q.json not found]")

    lines.append("")
    lines.append("=" * 60)
    lines.append("END OF SUMMARY")

    out_path.write_text("\n".join(lines) + "\n")
    print(f"\n[step 6] Summary written to {out_path}")


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

if __name__ == "__main__":
    extract_tar()
    b_ok, q_ok, r_ok = run_analysis()
    sync_results()
    write_summary()
    print("\nDone. Check results/new_conditions_summary.txt")
